apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: consul
  name: consul-api
  namespace: cabotage
spec:
  ports:
  - name:
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: consul
  type: ClusterIP
