kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: cabotage
  labels:
    app: ingress-cabotage
data:
  ssl-buffer-size: 16k
  use-proxy-protocol: 'false'
  compute-full-forwarded-for: 'false'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: cabotage
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: cabotage
