kind: Service
apiVersion: v1
metadata:
  name: ingress-cabotage
  namespace: cabotage
  labels:
    app: ingress-cabotage
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-2:220435833635:certificate/10c5ede5-c5d6-4fcc-af99-34bde566c7da"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  selector:
    app: ingress-cabotage
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80 #all goes to 80
