apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cabotage
  name: vault-server
data:
  config.json: |
      {
        "listener": [
          {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_cert_file": "/etc/tls/cert.pem",
              "tls_key_file": "/etc/tls/key.pem"
            }
          }
        ]
      }
