apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  namespace: cabotage
  name: vault
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8200
  selector:
    app: vault
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
