apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: request-certificate
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/serverautoapprove
  verbs:
  - create
