apiVersion: v1
kind: ServiceAccount
metadata:
  name: goldfish
  namespace: vault
  labels:
    org.pypi.infra.vault-access: "true"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: goldfish
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: request-certificate
subjects:
- kind: ServiceAccount
  name: goldfish
  namespace: vault
