apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cabotage
  name: goldfish
data:
  config.hcl: |
      listener "tcp" {
          address = "0.0.0.0:8000"
          tls_disable = 0
          pki_certificate "pki" {
              pki_path    = "/cabotage-ca/issue/cabotage-goldfish"
              common_name = "goldfish.cabotage.svc.cluster.local"
              alt_names   = ["goldfish.cabotage.svc", "goldfish.cabotage", "goldfish"]
          }
      }
      vault {
          address         = "https://vault.cabotage.svc.cluster.local"
          ca_cert         = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          tls_skip_verify = 0

          runtime_config  = "goldfish-secret/runtime-config"
      
          approle_login   = "null"
          approle_id      = "null"
      }
      disable_mlock = 1
