apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cabotage
  name: goldfish
data:
  config.hcl: |
      listener "tcp" {
          address = "0.0.0.0:8000"
          tls_disable = 0
          tls_cert_file = "/var/run/secrets/vault/chain.pem"
          tls_key_file = "/var/run/secrets/vault/key.pem"
      }
      vault {
          address         = "https://vault.cabotage.svc.cluster.local"
          ca_cert         = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          tls_skip_verify = 0

          runtime_config  = "goldfish-secret/runtime-config"
      
          approle_login   = "null"
          approle_id      = "null"
      }
      disable_mlock = 1
