apiVersion: v1
kind: Service
metadata:
  labels:
    app: goldfish
  namespace: cabotage
  name: goldfish
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: goldfish
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
