apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: cabotage
  labels:
    app: registry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
      name: registry
    spec:
      serviceAccountName: registry
      initContainers:
        - name: cabotage-enroller
          image: cabotage/sidecar:v1.0.0a1
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "kube_login"
            - "--namespace=$(NAMESPACE)"
            - "--vault-auth-kubernetes-role=cabotage-registry"
            - "--fetch-cert"
            - "--vault-pki-role=cabotage-registry"
            - "--pod-name=$(POD_NAME)"
            - "--pod-ip=$(POD_IP)"
            - "--service-names=registry"
            - "--additional-dns-names=localhost"
          volumeMounts:
            - name: vault-secrets
              mountPath: /var/run/secrets/vault
      containers:
        - name: cabotage-sidecar
          image: cabotage/sidecar:v1.0.0a1
          imagePullPolicy: Always
          args:
            - "maintain"
            - "--vault-pki-role=cabotage-registry"
          volumeMounts:
            - name: vault-secrets
              mountPath: /var/run/secrets/vault
        - name: cabotage-sidecar-tls
          image: cabotage/sidecar:v1.0.0a1
          imagePullPolicy: Always
          command: ["./ghostunnel"]
          args:
            - "server"
            - "--keystore=/var/run/secrets/vault/combined.pem"
            - "--cacert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
            - "--timed-reload=300s"
            - "--shutdown-timeout=10s"
            - "--connect-timeout=10s"
            - "--disable-authentication"
            - "--target=127.0.0.1:4999"
            - "--listen=0.0.0.0:5000"
          volumeMounts:
            - name: vault-secrets
              mountPath: /var/run/secrets/vault
          ports:
            - containerPort: 5000
              name: https
          livenessProbe:
            httpGet:
              path: /
              scheme: HTTPS
              port: 5000
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              scheme: HTTPS
              port: 5000
            initialDelaySeconds: 10
        - name: registry
          image: cabotage/registry:v1.0.0a1
          imagePullPolicy: Always
          args: ['/etc/docker/registry-local/config.yml']
          ports:
            - containerPort: 4999
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 4999
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 4999
            initialDelaySeconds: 10
          volumeMounts:
            - name: registry-config
              mountPath: /etc/docker/registry-local
            - name: vault-secrets
              mountPath: /var/run/secrets/vault
          resources:
            limits:
              memory: "60Mi"
              cpu: "50m"
      terminationGracePeriodSeconds: 5
      volumes:
        - name: vault-secrets
          emptyDir:
            medium: "Memory"
            sizeLimit: "1M"
        - name: registry-config
          configMap:
            name: registry-config
