apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: registry
  namespace: cabotage
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
      name: registry
    spec:
      serviceAccountName: registry
      initContainers:
        - name: cabotage-enroller
          image: cabotage/sidecar:v1.0.0a1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "kube_login"
            - "--namespace=$(NAMESPACE)"
            - "--vault-auth-kubernetes-role=cabotage-registry"
            - "--fetch-cert"
            - "--vault-pki-role=cabotage-registry"
            - "--pod-name=$(POD_NAME)"
            - "--pod-ip=$(POD_IP)"
            - "--service-names=registry"
            - "--additional-dns-names=localhost"
          volumeMounts:
            - name: vault-secrets
              mountPath: /var/run/secrets/vault
      containers:
        - name: cabotage-sidecar
          image: cabotage/sidecar:v1.0.0a1
          imagePullPolicy: Always
          args:
            - "maintain"
            - "--vault-pki-role=cabotage-registry"
          volumeMounts:
            - name: vault-secrets
              mountPath: /var/run/secrets/vault
        - name: cabotage-sidecar-tls
          image: cabotage/sidecar:v1.0.0a1
          imagePullPolicy: Always
          command: ["./ghostunnel"]
          args:
            - "server"
            - "--keystore=/var/run/secrets/vault/combined.pem"
            - "--cacert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
            - "--timed-reload=300s"
            - "--shutdown-timeout=10s"
            - "--connect-timeout=10s"
            - "--disable-authentication"
            - "--target=127.0.0.1:4999"
            - "--listen=0.0.0.0:5000"
          volumeMounts:
            - name: vault-secrets
              mountPath: /var/run/secrets/vault
          ports:
            - containerPort: 5000
              hostPort: 5000
              name: https
        - name: registry
          image: cabotage/registry:v1.0.0a1
          imagePullPolicy: Always
          env:
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              value: "MINIOACCESSKEY"
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              value: "MINIOSECRETKEY"
            - name: REGISTRY_STORAGE_S3_REGION
              value: "us-east-2"
            - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
              value: "https://minio.cabotage.svc.cluster.local:9000"
            - name: REGISTRY_STORAGE_S3_BUCKET
              value: "cabotage-registry"
            - name: REGISTRY_STORAGE_S3_ENCRYPT
              value: "false"
            - name: REGISTRY_STORAGE_S3_KEYID
              value: "mykeyid"
            - name: REGISTRY_STORAGE_S3_SECURE
              value: "true"
            - name: REGISTRY_STORAGE_S3_V4AUTH
              value: "true"
            - name: REGISTRY_STORAGE_S3_CHUNKSIZE
              value: "5242880"
          args: ['/etc/docker/registry-local/config.yml']
          ports:
            - containerPort: 4999
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 4999
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 4999
            initialDelaySeconds: 10
          volumeMounts:
            - name: registry-config
              mountPath: /etc/docker/registry-local
            - name: vault-secrets
              mountPath: /var/run/secrets/vault
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
      terminationGracePeriodSeconds: 5
      volumes:
        - name: vault-secrets
          emptyDir:
            medium: "Memory"
            sizeLimit: "1M"
        - name: registry-config
          configMap:
            name: registry-config
