apiVersion: v1
kind: Service
metadata:
  namespace: cabotage
  name: registry
  labels:
    app: registry
spec:
  clusterIP: None
  ports:
    - port: 5000
      name: registry
  selector:
    app: registry
