apiVersion: v1
kind: Service
metadata:
  namespace: cabotage
  name: minio
  labels:
    app: minio
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio
