apiVersion: v1
kind: Service
metadata:
  labels:
    app: builder
  namespace: cabotage
  name: builder
spec:
  ports:
  - port: 2375
    protocol: TCP
    targetPort: 2375
  selector:
    app: builder
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
