apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: cabotage-app
  name: cabotage-deployments
rules:
  - verbs:
      - get
      - list
      - create
      - patch
    apiGroups:
      - ''
    resources:
      - serviceaccounts
      - namespaces
      - secrets
  - verbs:
      - get
      - list
      - create
      - patch
    apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
  - verbs:
      - get
      - list
      - create
      - patch
      - delete
    apiGroups:
      - batch
    resources:
      - jobs
      - jobs/status
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - pods
      - pods/log
