apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: cabotage-app
  name: cabotage-deployments
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
