apiVersion: v1
kind: Service
metadata:
  labels:
    app: cabotage-app
  namespace: cabotage
  name: cabotage-app
spec:
  ports:
  - port: 8443
    name: https
  selector:
    app: cabotage-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
