apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: cabotage
  name: view-serviceaccounts
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
