apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: enrollment-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-serviceaccounts
subjects:
- kind: ServiceAccount
  namespace: cabotage
  name: enrollment-controller
