apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: cabotage
  name: enrollment-controller
  labels:
    app: enrollment-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: enrollment-controller
    spec:
      serviceAccountName: enrollment-controller
      initContainers:
        - name: cabotage-enroller
          image: cabotage/sidecar:v1.0.0a1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "kube_login"
            - "--vault-auth-kubernetes-role=cabotage-enrollment-controller"
            - "--no-unwrap"
          volumeMounts:
            - name: vault-token
              mountPath: /var/run/secrets/vault
      containers:
        - name: cabotage-sidecar
          image: cabotage/sidecar:v1.0.0a1
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "maintain"
            - "--vault-token-file=/var/run/secrets/vault/wrapped-vault-token"
            - "--unwrap"
          volumeMounts:
            - name: vault-token
              mountPath: /var/run/secrets/vault
        - name: enrollment-controller
          image: cabotage/enrollment-controller:v1.0.0a1
          args:
            - "--vault-token=@/var/run/secrets/vault/vault-token"
            - "--vault-addr=https://vault.cabotage.svc.cluster.local"
            - "--vault-cacert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          volumeMounts:
            - name: vault-token
              mountPath: /var/run/secrets/vault
          resources:
            limits:
              memory: "50Mi"
              cpu: "100m"
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: vault-token
          emptyDir:
            medium: "Memory"
            sizeLimit: "1M"
